name: "Set up s3 nix cache"
description: "Sets up nunu nix cache with automatic signing and upload"
inputs:
  substituters:
    description: Nix cache urls to use (space separated). First will be used to upload build outputs to
    required: true
  trusted_public_keys:
    description: Public keys of substitutors (space separated)
    required: true
  secret_keys:
    description: Secret keys for signing built outputs
    required: true
  aws_access_key_id:
    description: Access key ID for downloading and uploading artifacts
    required: true
  aws_secret_access_key:
    description: Secret access key for downloading and uploading artifacts
    required: true
runs:
  using: "node20"
  main: "dist/index.js"
